### ISSUE TITLE
Errato usare Articolo come tipo di Edge

### ISSUE THREAD

**Issue by fulcorno** [TdP-2016/Lab9#1]
Il multi-grafo dedinito in Model è di tipo <Autore, Articolo>.
Ciò non è corretto in quanto lo stesso Articolo può dare origine a più archi diversi (es. nel caso di un articolo a 4 nomi, ci saranno 12 archi che fanno riferimento allo stesso articolo).
Ciò è incompatibile con la rappresentazione come Set degli archi utilizzata da jGraphT.
Vedi: http://jgrapht.org/javadoc/org/jgrapht/Graph.html#addEdge(V,%20V,%20E) 
In questo caso gli archi successivi al primo non vengono aggiunti.

Suggerimento: definire una nuova classe (ad esempio sottoclasse di DefaultEdge), che all'interno abbia un campo che fa riferimento all'articolo.

**Comment by jimmy-sonny** [comment]
Corretto [b2fd50d](https://github.com/TdP-2016/Lab9/commit/b2fd50d6ef693565be964c735a201369d12560fa)
